volumes:
  data:

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  api:
    build: ./flaskr
    ports:
      - 5000:5000
