volumes:
  data:
  files:

services:
  converter:
    container_name: converter
    build: ./converter
    privileged: true
    ports:
      - 8000:8000
    volumes:
      - files:/app/files

  api:
    container_name: api
    build: ./flaskr
    privileged: true
    ports:
      - 6000:80
    volumes:
      - files:/app/files
