volumes:
  data:

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - APP_DB_NAME=postgres
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql

  api:
    container_name: api
    build: ./flaskr
    ports:
      - 6000:6000
    environment:
      - FLASK_DEBUG=1
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - APP_DB_NAME=postgres
    depends_on:
      - db
      - redis
    volumes:
      - ./flaskr:/app
      - ./files:/app/files

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
