volumes:
  data:

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - APP_DB_NAME=postgres
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql

  api:
    build: ./flaskr
    ports:
      - 6000:6000
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - APP_DB_NAME=postgres

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    volumes:
      - ./servers.json:/pgadmin4/servers.json
