volumes:
  data:

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - APP_DB_NAME=postgres
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql

  api:
    container_name: api
    image: ubuntu:latest
    working_dir: /app
    command: sh -c "apt-get update && apt-get install -y ffmpeg python3 python3-pip\
      && pip install --no-cache-dir -r requirements.txt && python3 app.py"
    ports:
      - 6000:6000
    environment:
      - FLASK_DEBUG=1
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - APP_DB_NAME=postgres
    depends_on:
      - db
      - redis
    volumes:
      - ./flaskr:/app
      - ./flaskr/files:/app/files

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  mail:
    container_name: mail
    image: python:3-alpine
    ports:
      - 7000:7000
    working_dir: /app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python3 app.py"
    volumes:
      - ./notificator:/app
      - ./flaskr/files:/app/files
    environment:
      - FLASK_DEBUG=1
